services:
  web:
    build: .
    command: sh -c "/app/wait-for-db.sh && python manage.py migrate && gunicorn --workers 2 config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - backend_network
    tty: true

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  redis:
    image: redis
    command:
      - redis-server
      - --save ""
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru
      - --vm.overcommit-memory 1
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network
    volumes:
      - redis_data:/data


  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info -s /var/run/celery/celerybeat-schedule --detach
    user: "1000:1000"
    env_file: .env
    volumes:
      - ./celery_beat:/app/celery_beat
    networks:
      - backend_network
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=INFO --detach
    user: "1000:1000"
    env_file: .env
    networks:
      - backend_network
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  redis_data:
