# Generated by Django 5.1.6 on 2025-03-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление'),
        ),
    ]
